Mubango/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from django.contrib.auth import views as auth_views

app_name = "mubango"
main = [
    url(r"^logout/", auth_views.LogoutView.as_view(), name="logout"),
    url(r"^account/", include("account.urls")),
    url(r"^business/", include("business.urls")),
    url(r"^event/", include("event.urls")),
    url(r"^offer/", include("offer.urls")),
    url(r"", include("core.urls")),
    url(r"^social-auth/", include("social_django.urls", namespace="social")),
    url(r"^admin/", admin.site.urls),
    url(r"^__debug__/", include(debug_toolbar.urls)),
]

urlpatterns = (
    [url(r"^mb/", include(main))]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "Mubango Admin"
admin.site.site_title = "Mubango Admin Portal"
admin.site.index_title = "Welcome to Mubango Admin Portal"


def show_toolbar(request):
    return True


SHOW_TOOLBAR_CALLBACK = show_toolbar

core/urls.py
from django.conf.urls import url
from . import views

app_name = "core"
urlpatterns = [
    url(
        r"^home/$",
        views.Index,
        name="home",
    )
]

review/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name = "review"
urlpatterns = [
    url(
        r"^add-review/$",
        login_required(views.save_review),
        name="save_review",
    ),
    url(
        r"^service/rating/$",
        login_required(views.add_service_rating),
        name="save_review",
    ),
    url(
        r"^all/$",
        login_required(views.ReviewList.as_view()),
        name="user_review_list",
    ),
    url(
        r"^update/(?P<pk>[\w|\W]+)/$",
        login_required(views.ReviewUpdate.as_view()),
        name="user_update",
    ),
    url(
        r"^delete/(?P<pk>[\w|\W]+)/$",
        login_required(views.ReviewDeleteView.as_view()),
        name="review_delete",
    ),
]

review/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from business.models import Business, Service
from common.models import DateModel
from django.contrib.auth.models import User


class ReviewManager(models.Manager):
    def get_queryset(self):
        return super(ReviewManager, self).get_queryset().filter(moderated=True)

    def get_review_for_a_specific_user(self, username):
        # get review for a specific user
        return self.get_queryset().filter(
            user__username=username,
        )

    def review_for_a_business(self, business):
        # includes review for a business
        return self.get_queryset().filter(
            business__name=business,
        )


class Review(DateModel):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    comment = models.TextField(blank=True, null=True)
    experience = models.CharField(max_length=200)
    image_1 = models.ImageField(null=True, blank=True)
    image_2 = models.ImageField(null=True, blank=True)
    image_3 = models.ImageField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    moderated = models.BooleanField(default=False)
    objects = models.Manager()  # The default manager.
    review_manager = ReviewManager()  # The review manager.

    class Meta:
        verbose_name_plural = "Reviews"

    def __str__(self):
        return "{} {} {}".format(self.id, self.user.username, self.business.name)


class BusinessServiceRating(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    rating = models.IntegerField(
        default=1, validators=[MaxValueValidator(5), MinValueValidator(1)]
    )
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    active = models.BooleanField(default=True)

    def __str__(self):
        return "{} {} {}".format(self.service.name, self.business.name, self.rating)

review/views.py
from django.http import JsonResponse
from django.shortcuts import redirect
from django.views.generic import ListView, UpdateView, DeleteView

from account.models import Profile
from .models import Review, BusinessServiceRating, Service
from business.models import Business


def save_review(request):
    if request.method == "POST" and request.is_ajax():
        print("req", request.POST, request.FILES)
        image1 = request.FILES.get("image_1")
        image2 = request.FILES.get("image_2")
        image3 = request.FILES.get("image_3")
        print("im", image1, image2, image3)
        comment = request.POST.get("comment")
        experience = request.POST.get("experience")
        user = request.user
        b_slug = request.POST.get("business_slug")
        business = Business.objects.get(slug=b_slug)
        Review.objects.create(
            business=business,
            user=user,
            comment=comment,
            experience=experience,
            image_1=image1,
            image_2=image2,
            image_3=image3,
        )
        data = {"status": 201, "response": "Review Saved Successfully"}
        return JsonResponse(data, safe=False)


def add_service_rating(request):
    if request.method == "POST" and request.is_ajax():
        user = request.user
        b_slug = request.POST.get("business_slug")
        business = Business.objects.get(slug=b_slug)
        service_name = request.POST.get("service_name")
        rating = int(request.POST.get("rating"))
        service, _ = Service.objects.get_or_create(name=service_name)
        business_service_rating, _ = BusinessServiceRating.objects.get_or_create(
            business=business,
            user=user,
            service=service,
        )
        business_service_rating.rating = rating
        business_service_rating.save()
        data = {"status": 200, "response": "Review Saved Successfully"}
        return JsonResponse(data, safe=False)


class ReviewList(ListView):
    model = Review
    template_name = "review/user_review_list.html"
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super(ReviewList, self).get_context_data(**kwargs)
        context["profile"] = Profile.objects.get(user=self.request.user)
        return context

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class ReviewUpdate(UpdateView):
    model = Review
    template_name = "review/update_review.html"
    paginate_by = 10
    fields = (
        "comment",
        "experience",
        "user",
        "business",
    )

    def form_valid(self, form):
        review = form.save(commit=False)
        business = Business.objects.get(slug=form.cleaned_data.get("business"))
        review.business = business
        review.save()

    def get_context_data(self, *args, **kwargs):
        context = super(ReviewUpdate, self).get_context_data(**kwargs)
        context["profile"] = Profile.objects.get(user=self.request.user)
        return context

    def get_success_url(self):
        return redirect("review:user_review_list")

    def dispatch(self, request, *args, **kwargs):
        """ Making sure that only authors can update stories """
        obj = self.get_object()
        print("entered")
        if obj.user != self.request.user:
            print("entered here")
            return redirect("review:user_review_list")
        return super(ReviewUpdate, self).dispatch(request, *args, **kwargs)


class ReviewDeleteView(DeleteView):
    model = Review
    template_name = "review/review_confirm_delete.html"
    success_url = "/mb/review/all/"

    def dispatch(self, request, *args, **kwargs):
        """ Making sure that only authors can update stories """
        obj = self.get_object()
        if obj.user != self.request.user:
            return redirect("review:user_review_list")
        return super(ReviewDeleteView, self).dispatch(request, *args, **kwargs)

review/templates/review/add_review.html
<div class="listingcomment">
    <div class="leavecomment">
        <h3>Rate us and Write a Review</h3>
        <form method="POST" enctype="multipart/form-data" action="{% url 'review:save_review' %}">
            <div id="review_status" style="color:green"></div>
            {% csrf_token %}
            <input type="hidden" id="business_slug" value="{{ request.resolver_match.kwargs.slug }}">
            <input placeholder="Title" type="text" id="experience" required>
            <textarea placeholder="Review" id="comment"></textarea>
            <div class="fieldformy">
                <span>Add Images</span>
                <input type="file" id="image_1">
                <input type="file" id="image_2">
                <input type="file" id="image_3">
            </div>
            <div class="fieldformy">
                <span>Rate the following(1=bad,5=Excellent)</span>
                <div class="fieldformy">
                    <div class="row">
                        <div class="col-md-3">
                         <span>Security
                <select id="security" class="cdropshere">
                    <option selected>1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                </span>
                        </div>
                        <div class="col-md-3">
                          <span>Music
                <select id="music" class="cdropshere">
                    <option selected>1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                </span>
                        </div>
                        <div class="col-md-3">
                          <span>Pricing
                <select class="cdropshere" id="pricing">
                    <option selected>1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                </span>
                        </div>
                        <div class="col-md-3">
                          <span>Amenities
                <select id="amenities" class="cdropshere">
                    <option selected>1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                </span>
                        </div>
                    </div>
                    <div class="row" style="margin-top: 20px">
                        <div class="col-md-3">
                         <span>Food
                <select class="cdropshere" id="food">
                    <option selected>1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                </span>
                        </div>
                        <div class="col-md-3">
                          <span>Service
                <select class="cdropshere" id="service">
                    <option selected>1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                </span>
                        </div>
                        <div class="col-md-3">
                          <span>Parking
                <select class="cdropshere" id="parking">
                    <option selected>1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>
                </span>
                        </div>
                        </div>
                    </div>
                    <div class="fieldformy">
                        <input id='btn_review' value="Submit Review" type="submit">
                    </div>
            </div>

        </form>
    </div>
</div>

review/templates/review/review_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
    <section style="margin-top: 30px">
        <form class="form-control" method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object.experience }}"?</p>
            <div class="row">
                <div class="col-md-2">
                    <a href="{% url 'review:user_review_list' %}" title="" class="btn btn-secondary">Cancel</a>
                </div>
                <div class="col-md-2">
                    <input class="btn btn-danger" type="submit" value="Confirm">

                </div>
            </div>

        </form>
    </section>
{% endblock content %}

review/templates/review/review_list.html
<div class="listingcomment">
    <h3>{{ review_count }} reviews for {{ object.name }}</h3>
    {% for review in object_list %}

        <div class="reviewssec">
            <div class="reviewinfo">
                <h4>{{ review.user |capfirst }} says...</h4>

                <span>{{ review.comment }}</span>
                <p>{{ review.experience }}</p>
            <div class="rgallery">
                {% if review.image_1 %}
                    <a href="{{ review.image_1.url }}" title="">
                        <img src="{{ review.image_1.url }}" alt=""></a>
                {% endif %}
                {% if review.image_2 %}
                    <a href="{{ review.image_2.url }}" title="">
                        <img src="{{ review.image_2.url }}" alt=""></a>
                {% endif %}
                {% if review.image_3 %}
                    <a href="{{ review.image_3.url }}" title="">
                        <img src="{{ review.image_3.url }}" alt=""></a>
                {% endif %}
            </div>
            </div>
        </div>

    {% endfor %}


</div>
<section>

    {% if is_paginated %}
        <div class="pagination">
            <ul>

                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a style="background: #3ebfdf" href="?page={{ page_obj.previous_page_number }}"
                           aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                {% endif %}

                <li class="page-item active">
                    <a style="background: #3ebfdf" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                        <span class="sr-only">(current)</span>
                    </a>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a style="background: #3ebfdf" href="?page={{ page_obj.next_page_number }}"
                           aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
</section>

review/templates/review/update_review.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
    <section style="margin-top: 20px">
        <div class="pbox">
            <div class="addlistingform">
                <form method="post" action="{% url 'review:user_update' object.pk %}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="fieldformy">
                                <input type="hidden" name="business" value="{{ object.business.slug }}"/>
                                <input type="hidden" name="user" value="{{ object.user }}">
                                <span>Comment</span>
                                <input type="text" name="experience" value="{{ object.experience }}">
                            </div>
                            <div class="fieldformy">
                                <span>Experience</span>
                                <input type="text" name="comment" value="{{ object.comment }}">
                            </div>
                            {% if object.image_1 %}
                                <div class="fieldformy">
                                    <span>ReviewImage1</span>
                                    <img src="{{ object.image_1.url }}"/>
                                </div>
                            {% endif %}
                            {% if object.image_2 %}
                                <div class="fieldformy">
                                    <span>ReviewImage2</span>
                                    <img src="{{ object.image_2.url }}"/>
                                </div>
                            {% endif %}
                            {% if object.image_3 %}
                                <div class="fieldformy">
                                    <span>ReviewImage3</span>
                                    <img src="{{ object.image_3.url }}"/>
                                </div>
                            {% endif %}
                        </div>
                        <div class="col-lg-12">
                            <div class="formaction">
                                <div class="row">
                                    <div class="col-md-2">
                                        <input class="btn btn-primary" type="submit" name="Update" value="Update">
                                    </div>
                                    <div class="col-md-2">
                                        <a href="{% url 'review:user_review_list' %}"  title="" class="btn btn-secondary">Cancel</a>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock content %}

review/templates/review/user_review_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
    <section style="margin-top: 20px">
        <div class="row justify-content-center">
            <div class="col-lg-10">
                <div class="dashboradsec">
                    <h3>Reviews</h3>
                    {% for review in review_list %}
                        <div class="pbox">
                            <div class="reviewssec">
                                <div class="reviewthumb"><img src="{{ profile.image.url }}"
                                                              alt="{{ profile.image.url }}"></div>
                                <div class="reviewinfo">
                                    <h3>{{ review.user }} <i>You posted a review on <strong></strong></i></h3>
                                    <span>{{ review.date_added }}</span>
                                    <p>{{ review.experience }}</p>
                                    <p>{{ review.comment }}</p>
                                    <div class="reviewaction">
                                        <a href="{% url 'review:user_update' review.pk %}" title=""><i class="flaticon-eraser"></i> Edit</a>
                                        <a href="{% url 'review:review_delete' review.pk %}" title=""><i class="flaticon-dustbin"></i> Remove</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    {% if is_paginated %}
        <div class="pagination">
            <ul>

                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a style="background: #3ebfdf" href="?page={{ page_obj.previous_page_number }}"
                           aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                {% endif %}

                <li class="page-item active">
                    <a style="background: #3ebfdf" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                        <span class="sr-only">(current)</span>
                    </a>
                </li>

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a style="background: #3ebfdf" href="?page={{ page_obj.next_page_number }}"
                           aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    {% endif %}
{% endblock content %}