Mubango/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from django.contrib.auth import views as auth_views

app_name = "mubango"
main = [
    url(r"^logout/", auth_views.LogoutView.as_view(), name="logout"),
    url(r"^account/", include("account.urls")),
    url(r"^business/", include("business.urls")),
    url(r"^event/", include("event.urls")),
    url(r"^offer/", include("offer.urls")),
    url(r"", include("core.urls")),
    url(r"^social-auth/", include("social_django.urls", namespace="social")),
    url(r"^admin/", admin.site.urls),
    url(r"^__debug__/", include(debug_toolbar.urls)),
]

urlpatterns = (
    [url(r"^mb/", include(main))]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "Mubango Admin"
admin.site.site_title = "Mubango Admin Portal"
admin.site.index_title = "Welcome to Mubango Admin Portal"


def show_toolbar(request):
    return True


SHOW_TOOLBAR_CALLBACK = show_toolbar

account/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name = "account"

urlpatterns = [
    url(r"^home/$", views.Home, name="home"),
    url(r"^login/$", views.LoginView, name="login"),
    url(r"^logout/$", views.LogoutView, name="logout"),
    url(r"^signup/$", views.SignupView, name="signup"),
    url(
        r"^ajax/validate_username/$", views.validate_username, name="validate_username"
    ),
    url(
        r"^ajax/validate_phonenumber/$",
        views.validate_phonenumber,
        name="validate_phone",
    ),
    url(r"^ajax/validate_email/$", views.validate_email, name="validate_email"),
    url(r"^ajax/validate_email/$", views.validate_email, name="validate_email"),
    url(
        r"^profile/(?P<slug>[0-9a-f-]+)/$",
        login_required(views.ProfileDetail.as_view()),
        name="profile_detail",
    ),
    url(
        r"^profile/(?P<slug>[0-9a-f-]+)/update/$",
        login_required(views.UpdateProfile),
        name="profile_update",
    ),
    url(
        r"^password/(?P<slug>[0-9a-f-]+)/update/$",
        login_required(views.UpdatePassword),
        name="password_update",
    ),
]

business/urls.py
from django.conf.urls import url
from . import views

app_name = "business"
urlpatterns = [
    url(
        r"^search-all/(?P<state>[\w-]+)/$",
        views.get_all_business,
        name="get_all_business",
    ),
    url(
        r"^search-single/(?P<name>[\w|\W]+)/(?P<state>[\w-]+)/$",
        views.search_for_a_specific_business,
        name="search_for_a_specific_business",
    ),
    url(
        r"^all/(?P<state>[\w|\W]+)/$",
        views.ClubListView.as_view(),
        name="get_all_clubs",
    ),
    url(
        r"^list-by-region/(?P<region>[\w|\W]+)/$",
        views.ClubListByRegion.as_view(),
        name="get_clubs_region",
    ),
    url(
        r"^(?P<slug>[\w-]+)/$",
        views.ClubDetailView.as_view(),
        name="club_detail",
    ),
]

core/urls.py
from django.conf.urls import url
from . import views

app_name = "core"
urlpatterns = [
    url(
        r"^home/$",
        views.Index,
        name="home",
    )
]

event/urls.py
from django.conf.urls import url
from . import views

app_name = "event"
urlpatterns = [
    url(
        r"^search-single/(?P<name>[\w|\W]+)/(?P<state>[\w-]+)/$",
        views.search_for_a_specific_event,
        name="search_for_a_specific_event",
    ),
    url(
        r"^search-all/(?P<state>[\w-]+)/$",
        views.get_all_events_in_a_state,
        name="get_all_events",
    ),
    url(
        r"^(?P<slug>[\w-]+)/$",
        views.EventDetailView.as_view(),
        name="event_detail",
    ),
    url(
        r"^all/(?P<state>[\w|\W]+)/$",
        views.EventListView.as_view(),
        name="get_all_events",
    ),
    url(
        r"^list-by-region/(?P<region>[\w|\W]+)/$",
        views.EventListByRegion.as_view(),
        name="get_events_region",
    ),
]

offer/urls.py
from django.conf.urls import url
from . import views

app_name = "offer"
urlpatterns = [
    url(
        r"^list-by-region/(?P<region>[\w|\W]+)/$",
        views.OfferListByRegion.as_view(),
        name="get_offer_region",
    ),
    url(
        r"^(?P<slug>[\w-]+)/$",
        views.OfferDetailView.as_view(),
        name="offer_detail",
    ),
    url(
        r"^all/(?P<state>[\w|\W]+)/$",
        views.OfferListView.as_view(),
        name="get_all_offers",
    ),
]

core/views.py
from django.shortcuts import render
from business.models import Business
from event.models import Event
from account.models import Profile
from account.context_processor import get_user_state_and_profile_id

# Create your views here.
from offer.models import Offer


def Index(request):
    if request.method == "GET":
        if not request.user.is_anonymous:
            profile = Profile.objects.get(user=request.user)
            clubs_featured = Business.business_manager.six_closest_clubs(
                profile.get_state()
            )
            club_currently_hot_list = Business.business_manager.currently_hot_clubs(
                profile.get_state()
            )
            event_featured_list = Event.event_manager.upcoming_events(
                profile.get_state()
            )
            offer_featured_list = Offer.offer_manager.upcoming_offers(
                profile.get_state()
            )
            return render(
                request,
                "core/index.html",
                {
                    "clubs_featured": clubs_featured,
                    "club_currently_hot_list": club_currently_hot_list,
                    "event_featured_list": event_featured_list,
                    "offer_featured_list": offer_featured_list,
                    "club_list_six_header": "Featured Clubs in your Area",
                },
            )
        else:
            state = get_user_state_and_profile_id(request)
            clubs_featured = Business.business_manager.six_closest_clubs(
                state["user_state"]
            )
            club_currently_hot_list = Business.business_manager.currently_hot_clubs(
                state["user_state"]
            )
            event_featured_list = Event.event_manager.upcoming_events(
                state["user_state"]
            )
            offer_featured_list = Offer.offer_manager.upcoming_offers(
                state["user_state"]
            )

            return render(
                request,
                "core/index.html",
                {
                    "clubs_featured": clubs_featured,
                    "club_currently_hot_list": club_currently_hot_list,
                    "event_featured_list": event_featured_list,
                    "club_list_six_header": "Featured Clubs in {}".format(
                        state["user_state"]
                    ),
                    "offer_featured_list": offer_featured_list,
                },
            )

core/templates/core/base.html
{% load static %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{% block head_title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="CreativeLayers">
    {% block extra_head %}
    {% endblock %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-grid.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}"/>
</head>


<body class="full-height" id="scrollup">
<div class="page-loading">
    <img src="{% static 'images/loader.gif' %}" alt=""/>
    <span>Skip Loader</span>
</div>

<div class="theme-layout">

    {% include 'core/navbar.html' %}
    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}
    {% include 'account/account.html' %}

    {% include "core/footer.html" %}
    {% include "core/scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</div>
</body>
</html>

core/templates/core/footer.html
<footer>
		<div class="block">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="footersec">
							<div class="flogo"><a href="#" title=""><img src="http://placehold.it/175x40" alt="" /></a></div>
							<ul>
								<li><a href="#" title="">Home</a></li>
								<li><a href="#" title="">Explore</a></li>
								<li><a href="#" title="">Listings</a></li>
								<li><a href="#" title="">Destinations</a></li>
								<li><a href="#" title="">Pages</a></li>
							</ul>
							<span>Collins Street West, Victoria 8007, Australia.</span>
							<span>+1 246-345-0695</span>
							<span>info@example.com</span>
							<div class="social">
								<a href="#" title=""><i class="fa fa-facebook"></i></a>
								<a href="#" title=""><i class="fa fa-twitter"></i></a>
								<a href="#" title=""><i class="fa fa-instagram"></i></a>
								<a href="#" title=""><i class="fa fa-pinterest"></i></a>
								<a href="#" title=""><i class="fa fa-dribbble"></i></a>
								<a href="#" title=""><i class="fa fa-google"></i></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="bottomline">
			<a href="#scrollup" class="scrollup" title=""><i class="fa fa-angle-up"></i></a>
			<span>© 2018 Find&Go All rights reserved. Design by Creative Layers</span>
		</div>
	</footer>

core/templates/core/navbar.html
{% load static %}
<div class="responsiveheader">
    <div class="rheader">
        <span><img src="{% static 'images/ricon.png' %}" alt=""/></span>
        <div class="logo">
            <a href="#" title=""><img src="http://placehold.it/164x37" alt=""/></a>
        </div>
        <div class="extras">
            <span class="accountbtn"><i class="flaticon-avatar"></i></span>
        </div>
    </div>
    <div class="rnaver">
        <span class="closeresmenu"><i>x</i>Close</span>
        <div class="logo"><a href="#" title=""><img src="http://placehold.it/175x40" alt=""/></a></div>
        <div class="extras">
        </div>
        <ul>
            <li class="menu-item-has-children">
                <a href="{% url 'core:home' %}" title="">Home</a>
            </li>
            <li class="menu-item-has-children">
                <a href="{% url 'business:get_all_clubs' state=user_state %}" title="">Clubs</a>
                <ul>
                    <li><a href="{% url 'business:get_all_clubs' state=user_state %}" title="">View Clubs</a></li>

                </ul>
            </li>
            <li class="menu-item-has-children">
                <a href="{% url 'event:get_all_events' state=user_state %}" title="">Events</a>
                <ul>
                    <li><a href="{% url 'event:get_all_events' state=user_state %}" title="">View Events</a></li>

                </ul>
            </li>
            <li class="menu-item-has-children">
                <a href="" title="">Offers</a>
                <ul>
                    <li><a href="{% url 'offer:get_all_offers' state=user_state %}" title="">View Offers</a></li>

                </ul>
            </li>
            {% if user.is_authenticated %}
                <li class="menu-item-has-children">
                    <a href="#" title="">Account</a>
                    <ul>
                        <li><a href="{% url 'account:profile_detail' profile_id %}" title="">Profile</a></li>
                    </ul>
                </li>
            {% endif %}
            {% if user.is_superuser %}
                <li class="menu-item-has-children">
                    <a href="/mb/admin/">Admin</a>
                </li>
            {% endif %}

        </ul>
    </div>
</div><!-- Responsive header -->

<header class="sticktop">
    <div class="logo">
        <a href="#" title=""><img src="http://placehold.it/164x37" alt=""/></a>
    </div>
    <div class="extras">
        {#			<a href="add-listing.html" title=""><img src="{% static 'images/ricon.png' %}" alt="" /> Add Listing</a>#}
        <span class="accountbtn"><i class="flaticon-avatar"></i></span>
    </div>
    <nav>
        <ul>
            <li class="menu-item-has-children">
                <a href="{% url 'core:home' %}" title="">Home</a>
            </li>
            <li class="menu-item-has-children">
                <a href="{% url 'business:get_all_clubs' state=user_state %}" title="">Clubs</a>
                <ul>
                    <li><a href="{% url 'business:get_all_clubs' state=user_state %}" title="">View Clubs</a></li>

                </ul>
            </li>
            <li class="menu-item-has-children">
                <a href="{% url 'event:get_all_events' state=user_state %}" title="">Events</a>
                <ul>
                    <li><a href="{% url 'event:get_all_events' state=user_state %}" title="">View Events</a></li>

                </ul>
            </li>
            <li class="menu-item-has-children">
                <a href="" title="">Offers</a>
                <ul>
                    <li><a href="{% url 'offer:get_all_offers' state=user_state %}" title="">View Offers</a></li>

                </ul>
            </li>
            {% if user.is_authenticated %}
                <li class="menu-item-has-children">
                    <a href="#" title="">Account</a>
                    <ul>
                        <li><a href="{% url 'account:profile_detail' profile_id %}" title="">Profile</a></li>
                    </ul>
                </li>
            {% endif %}
            {% if user.is_superuser %}
                <li class="menu-item-has-children">
                    <a href="/mb/admin/">Admin</a>
                </li>
            {% endif %}

        </ul>
    </nav>
</header>

core/templates/core/scripts.html
{% load static %}
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/modernizr.js' %}" type="text/javascript"></script>
<script src="{% static 'js/script.js' %}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/wow.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/slick.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/dropdown.js' %}" type="text/javascript"></script>
<script src="{% static 'js/isotop.js' %}" type="text/javascript"></script>
<script src="{% static 'js/custom_script.js' %}" type="text/javascript"></script>
<script src="{% static 'js/jquery.nicescroll.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/value.js' %}" type="text/javascript"></script>
<script type="text/javascript" src="{% static 'js/jq.aminoSlider.js' %}"></script>
<script type="text/javascript" src="{% static 'js/date-time-picker.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/account.js' %}"></script>
<script type="text/javascript" src="{% static 'js/map.js' %}"></script>
<script type="text/javascript" src="{% static 'js/map1.js' %}"></script>
<script type="text/javascript" src="{% static 'js/map2.js' %}"></script>
<script type="text/javascript" src="{% static 'js/parallax.js' %}"></script>
<script type="text/javascript" src="{% static 'js/search_script.js' %}"></script>
<script type="text/javascript" src="{% static 'js/search_script.js' %}"></script>
<script type="text/javascript" src="{% static 'js/review.js' %}"></script>