Mubango/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar
from django.contrib.auth import views as auth_views

app_name = "mubango"
main = [
    url(r"^logout/", auth_views.LogoutView.as_view(), name="logout"),
    url(r"^account/", include("account.urls")),
    url(r"^business/", include("business.urls")),
    url(r"^event/", include("event.urls")),
    url(r"^offer/", include("offer.urls")),
    url(r"", include("core.urls")),
    url(r"^social-auth/", include("social_django.urls", namespace="social")),
    url(r"^admin/", admin.site.urls),
    url(r"^__debug__/", include(debug_toolbar.urls)),
]

urlpatterns = (
    [url(r"^mb/", include(main))]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "Mubango Admin"
admin.site.site_title = "Mubango Admin Portal"
admin.site.index_title = "Welcome to Mubango Admin Portal"


def show_toolbar(request):
    return True


SHOW_TOOLBAR_CALLBACK = show_toolbar

business/urls.py
from django.conf.urls import url
from . import views

app_name = "business"
urlpatterns = [
    url(
        r"^search-all/(?P<state>[\w-]+)/$",
        views.get_all_business,
        name="get_all_business",
    ),
    url(
        r"^search-single/(?P<name>[\w|\W]+)/(?P<state>[\w-]+)/$",
        views.search_for_a_specific_business,
        name="search_for_a_specific_business",
    ),
    url(
        r"^all/(?P<state>[\w|\W]+)/$",
        views.ClubListView.as_view(),
        name="get_all_clubs",
    ),
    url(
        r"^list-by-region/(?P<region>[\w|\W]+)/$",
        views.ClubListByRegion.as_view(),
        name="get_clubs_region",
    ),
    url(
        r"^(?P<slug>[\w-]+)/$",
        views.ClubDetailView.as_view(),
        name="club_detail",
    ),
]

core/urls.py
from django.conf.urls import url
from . import views

app_name = "core"
urlpatterns = [
    url(
        r"^home/$",
        views.Index,
        name="home",
    )
]

business/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from phonenumber_field.modelfields import PhoneNumberField
from common.models import DateModel, Guest, Social, OpeningTime
from address.models import AddressField
from simple_search import search_filter
from django_resized import ResizedImageField


class Service(models.Model):
    name = models.CharField(max_length=80)
    icon = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class BusinessManager(models.Manager):
    def get_queryset(self):
        return super(BusinessManager, self).get_queryset().filter(active=True)

    def get_specific_business(self, name, state):
        query = name
        search_fields = ["name"]
        f = search_filter(search_fields, query)
        qs = self.get_queryset().filter(f)
        result = qs.filter(
            address__locality__state__name__icontains=state,
        )
        return result

    def top_rated_club(self, state):
        # top rated clubs
        return self.get_queryset().filter(
            address__locality__state__name__icontains=state, type="club", rating__gte=4
        )

    def six_closest_clubs(self, state):
        return (
            self.get_queryset()
            .filter(
                address__locality__state__name__icontains=state,
                type="club",
                featured=True,
            )
            .order_by("date_last_modified")[:6]
        )

    def closest_clubs(self, state):
        return (
            self.get_queryset()
            .filter(
                address__locality__state__name__icontains=state,
                type="club",
            )
            .order_by("date_last_modified")
        )

    def currently_hot_clubs(self, state):
        # currently hot clubs
        return self.get_queryset().filter(
            address__locality__state__name__icontains=state,
            type="club",
            currently_hot=True,
            featured=True,
        )


class Business(DateModel):
    category = [
        ("club", "Club"),
        ("organization", "Organization"),
        ("other", "Other"),
    ]
    name = models.CharField(max_length=200, db_index=True)
    description = models.CharField(blank=True, null=True, max_length=200)
    slug = models.SlugField(
        max_length=255,
        help_text="Unique value for product page URL, created from name.",
        unique=True,
    )
    email = models.EmailField(blank=True, null=True)
    phone_number = PhoneNumberField()
    active = models.BooleanField(default=False)
    type = models.CharField(max_length=30, choices=category, default="other")
    address = AddressField()
    currently_hot = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    openning_times = models.ManyToManyField(OpeningTime)
    objects = models.Manager()  # The default manager.
    business_manager = BusinessManager()  # The useroffer manager.

    def __str__(self):
        return "{} {}".format(self.name, self.active)

    def as_dict(self):
        return {
            "name": self.name,
            "location": self.address.raw,
            "phone_number": "{}-{}".format(
                self.phone_number.country_code, self.phone_number.national_number
            ),
        }

    def get_phone_number(self):
        return "{}-{}".format(
            self.phone_number.country_code, self.phone_number.national_number
        )

    def get_address(self):
        return self.address.raw

    def get_absolute_url(self):
        return reverse("business:club_detail", args=[str(self.slug)])

    def get_thumbnail(self):
        business_image = self.images.all().filter(img_category="thumbnail")
        if business_image:
            thumbnail = business_image[0].image.url
            return thumbnail

    def get_gallery(self):
        return self.images.all().filter(img_category="other")

    def get_social(self):
        return self.social.all()

    def get_slideshow(self):
        return self.images.all().filter(img_category="slideshow")

    def get_latitude(self):
        return self.address.as_dict()["latitude"]

    def get_longitude(self):
        return self.address.as_dict()["longitude"]

    def calculate_rating(self):
        from review.models import BusinessServiceRating

        count = 0
        total_rating = 0
        review_rating = BusinessServiceRating.objects.filter(business__slug=self.slug)
        for business_rating in review_rating:
            count += 1
            total_rating = total_rating + business_rating.rating
        try:
            return int(total_rating / count)
        except ZeroDivisionError:
            return 0

    def get_price_type(self):
        price_mapping = {1: "$", 2: "$$", 3: "$$$", 4: "$$$$", 5: "$$$$$"}
        from review.models import BusinessServiceRating

        count = 0
        total_rating = 0
        review_rating = BusinessServiceRating.objects.filter(
            business__slug=self.slug, service__name="Pricing"
        )
        for business_rating in review_rating:
            count += 1
            total_rating = total_rating + business_rating.rating
        try:
            return price_mapping[int(total_rating / count)]
        except ZeroDivisionError:
            return "$"

    class Meta:
        verbose_name_plural = "Businesses"


class VisitorCount(models.Model):
    """
    can be used to keep track of users visiting business e.g club for a specific date
    """

    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    visitor = models.ManyToManyField(User)
    count = models.IntegerField(default=0)
    date_time = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "VisitorCount"

    def __str__(self):
        return "{} {}".format(self.business.name, self.count)


class BusinessImage(DateModel):
    category = [
        ("thumbnail", "thumbnail"),
        ("other", "other"),
        ("top_slideshow", "slideshow"),
    ]
    business = models.ForeignKey(
        Business, related_name="images", on_delete=models.CASCADE
    )
    image = ResizedImageField(size=[480, 350], quality=75)
    img_category = models.CharField(max_length=20, choices=category, default="other")

    def __str__(self):
        return "{} {}".format(self.business.name, self.img_category)

    class Meta:
        db_table = "business_images"


class BusinessSocial(models.Model):
    business = models.ForeignKey(
        Business, related_name="social", on_delete=models.CASCADE
    )
    social = models.ForeignKey(Social, on_delete=models.CASCADE)
    url = models.URLField()
    active = models.BooleanField(default=False)

    def __str__(self):
        return "{} {}".format(self.business.name, self.social.name)

club/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from common.models import Address, DateModel, Rating, Guest


class Club(DateModel):
    name = models.CharField(max_length=200)
    email = models.EmailField(blank=True, null=True)
    phone_number = PhoneNumberField()
    active = models.BooleanField(default=False)
    address = models.ForeignKey(Address, on_delete=models.PROTECT)
    price_type = models.CharField(max_length=10, null=True, blank=True)  # e.g $$$ or $$
    rating = models.ForeignKey(Rating, on_delete=models.PROTECT, null=True, blank=True)

    def __str__(self):
        return "{} {}".format(self.name, self.active)

    class Meta:
        verbose_name_plural = "Clubs"


class VisitorCount(DateModel):
    """
    can be used to keep track of users visiting clubs for a specific date
    """

    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    visitor = models.ManyToManyField(User)
    count = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = "Trending"

    def __str__(self):
        return "{} {}".format(self.club.name, self.count)


class Trending(DateModel):
    club = models.ForeignKey(Club, on_delete=models.CASCADE)
    thumbs_up_count = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = "Trending"

    def __str__(self):
        return "{} {}".format(self.club.name, self.thumbs_up_count)

common/models.py
from django.db import models
from address.models import AddressField
from django.utils.translation import ugettext_lazy as _


class MusicGenre(models.Model):
    name = models.CharField(max_length=120, unique=True)

    def __str__(self):
        return self.name


class Guest(models.Model):
    first_name = models.CharField(max_length=120)
    last_name = models.CharField(max_length=120)

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)


class Social(models.Model):
    name = models.CharField(max_length=120)
    icon = models.CharField(max_length=120)

    def __str__(self):
        return "{} {}".format(self.name, self.icon)


class Venue(models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField(null=True, blank=True)
    capacity = models.IntegerField(null=True, blank=True)
    address = AddressField()

    def __str__(self):
        return "{} {}".format(self.name, self.description)


class DateModel(models.Model):
    """
    An abstract base class model that provides self-
    . fields.
    updating ``created`` and ``modified``
    """

    date_last_modified = models.DateField(auto_now=True)
    date_added = models.DateField(auto_now=True)

    class Meta:
        abstract = True


WEEKDAYS = [
    (1, _("Monday")),
    (2, _("Tuesday")),
    (3, _("Wednesday")),
    (4, _("Thursday")),
    (5, _("Friday")),
    (6, _("Saturday")),
    (7, _("Sunday")),
]


class OpeningTime(models.Model):

    weekday = models.IntegerField(choices=WEEKDAYS, unique=True)
    from_hour = models.TimeField()
    to_hour = models.TimeField()

    class Meta:
        verbose_name = "OpeningTime"

    def __str__(self):
        return "{}-{}".format(self.from_hour, self.to_hour)

review/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from business.models import Business, Service
from common.models import DateModel
from django.contrib.auth.models import User


class ReviewManager(models.Manager):
    def get_queryset(self):
        return super(ReviewManager, self).get_queryset().filter(moderated=True)

    def get_review_for_a_specific_user(self, username):
        # get review for a specific user
        return self.get_queryset().filter(
            user__username=username,
        )

    def review_for_a_business(self, business):
        # includes review for a business
        return self.get_queryset().filter(
            business__name=business,
        )


class Review(DateModel):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    comment = models.TextField(blank=True, null=True)
    experience = models.CharField(max_length=200)
    image_1 = models.ImageField(null=True, blank=True)
    image_2 = models.ImageField(null=True, blank=True)
    image_3 = models.ImageField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    moderated = models.BooleanField(default=False)
    objects = models.Manager()  # The default manager.
    review_manager = ReviewManager()  # The review manager.

    class Meta:
        verbose_name_plural = "Reviews"

    def __str__(self):
        return "{} {} {}".format(self.id, self.user.username, self.business.name)


class BusinessServiceRating(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    rating = models.IntegerField(
        default=1, validators=[MaxValueValidator(5), MinValueValidator(1)]
    )
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    active = models.BooleanField(default=True)

    def __str__(self):
        return "{} {} {}".format(self.service.name, self.business.name, self.rating)

business/views.py
from django.shortcuts import HttpResponse, render
from .models import Business, BusinessSocial
from review.models import BusinessServiceRating, Review
import json
from django.views.generic import ListView, DetailView
from django.views.generic.list import MultipleObjectMixin


# Create your views here.


def get_all_business(request, state):
    if request.method == "GET":
        response = [
            obj.as_dict() for obj in Business.business_manager.closest_clubs(state)
        ]
        return HttpResponse(
            json.dumps({"data": response}), content_type="application/json"
        )


def search_for_a_specific_business(request, name, state):
    if request.method == "GET":
        response = [
            obj.as_dict()
            for obj in Business.business_manager.get_specific_business(name, state)
        ]
        return HttpResponse(
            json.dumps({"data": response}), content_type="application/json"
        )


class ClubListView(ListView):
    paginate_by = 16
    model = Business
    template_name = "business/clubs/clubs_list_all.html"

    def get_context_data(self, **kwargs):
        context = super(ClubListView, self).get_context_data(**kwargs)
        context["club_list"] = Business.business_manager.closest_clubs(
            self.kwargs.get("state")
        )
        return context


class ClubDetailView(MultipleObjectMixin, DetailView):
    model = Business
    template_name = "business/clubs/club_detail.html"
    paginate_by = 5

    def get_context_data(self, **kwargs):
        object_list = Review.objects.filter(business__slug=self.kwargs.get("slug"))
        context = super(ClubDetailView, self).get_context_data(
            object_list=object_list, **kwargs
        )
        context["review_count"] = Review.objects.filter(
            business__slug=self.kwargs.get("slug")
        ).count()
        amenities = BusinessServiceRating.objects.filter(
            business__slug=self.kwargs.get("slug")
        ).select_related("service")

        context["business_social"] = BusinessSocial.objects.filter(
            business__slug=self.kwargs.get("slug"), active=True
        )
        context["club_amenities"] = amenities
        return context


class ClubListByRegion(ListView):
    model = Business
    template_name = "business/clubs/club_search_by_region.html"
    paginate_by = 16

    def get_queryset(self):
        qs = Business.business_manager.closest_clubs(self.kwargs.get("region"))
        return qs

business/templates/business/clubs/club_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}

    <section>
        <div class="block no-padding">
            <div class="container fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="sl-slider" id="makeslider">
                            {% for img in object.get_slideshow %}
                                <div class="slg-box"><img src="{{ img.image.url }}" alt=""/></div>
                            {% endfor %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="block no-padding gray">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="slhead">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="sltitle">
                                        <h1>{{ object.name|capfirst }}</h1>
                                        <ul class="listmetas">
                                            <li><span class="rated">{{ object.calculate_rating }}</span>{{ object.calculate_rating }}
                                                Ratings
                                            </li>
                                            <li><a href="#" title=""><i
                                                    class="flaticon-chef"></i> {{ object.type|capfirst }}</a></li>
                                            <li>
                                                <div class="currency"><i>{{ object.get_price_type }}</i></div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="slbtnsspans">
                                        <span><i class="flaticon-pin"></i>{{ object.get_address }}</span>
                                        <span><i class="flaticon-phone-call"></i>{{ object.get_phone_number }}</span>
                                        <div class="slbtns">
                                            <div class="sharelisting">
                                                <a href="#" title=""><i class="flaticon-share"></i>Share</a>
                                                <div class="sharebtns">
                                                    {% for social in object.get_social %}
                                                        <a href="{{ social.url }}" title=""><i
                                                                class="fa fa-{{ social.social.icon }}"></i></a>
                                                    {% endfor %}
                                                </div>
                                            </div>
                                            {#                                            <a onclick="add_review()" title=""><i class="flaticon-note"></i>Add review</a>#}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="block">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 column">
                        <div class="bbox">
                            <h3>Description</h3>
                            <div class="ldesc">
                                <p>{{ object.description }}</p>
                            </div>
                        </div>
                        <div class="bbox">
                            <h3>Amenities</h3>
                            <div class="amenties">
                                {% for amenities in club_amenities %}
                                    <span><i
                                            class="flaticon-{{ amenities.service.icon }}"></i>{{ amenities.service.name }}</span>
                                {% endfor %}
                            </div>
                        </div>
                     <div class="bbox">
                            <div>
                                {% include 'review/review_list.html' %}
                            </div>
                        </div>

                        <div class="bbox">
                            {% if user.is_authenticated%}

                            <div>
                                {% include 'review/add_review.html' %}
                            </div>
                            {% endif %}
                        </div>
                        <div class="bbox">
                            <h3>Gallery</h3>
                            <ul class="gallerylistin">
                                {% for img in object.get_gallery %}
                                    <li><img src="{{ img.image.url }}" alt=""/></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4 column">
                        <div class="openclosetiming">
                            <h3>Hours of Operations</h3>
                            {% for opening_times in object.openning_times.all %}
                                <span>{{ opening_times.get_weekday_display }} <i>{{ opening_times.from_hour }} - {{ opening_times.to_hour }}</i></span>
                            {% endfor %}
                        </div>
                        <div class="blocation">
                            <h3>Location <a href="#" title="">Get Direction</a></h3>
                            <div class="contact-map">
                                <div id="map">&nbsp;</div>
                            </div>
                            <span>{{ object.get_address }}</span>
                            <span>{{ object.get_phone_number }}</span>
                            <span>{{ object.email }}</span>
                            <div class="wsocial">
                                {% for social in business_social %}
                                    <a href="{{ social.url }}" title=""><i
                                            class="fa fa-{{ social.social.icon }}"></i></a>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="cbusiness">
                            <h3>Contact business</h3>
                            <form>
                                <label>Your Name *</label>
                                <input type="text" placeholder="Ali TUF..."/>
                                <label>Your Email Address*</label>
                                <input type="text" placeholder="demo@demo.com"/>
                                <label>Your Message</label>
                                <textarea placeholder="demo@demo.com"></textarea>
                                <button type="submit">Send Message</button>
                            </form>
                        </div>
                        <div class="cad">
                            <div class="ad"><img src="http://placehold.it/360x220" alt=""/></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>
    <script type="text/javascript">
        var disqus_config = function () {
            this.page.url = '{{ request.build_absolute_uri }}.html'
            console.log('kkdkd', this.page.url);
            this.page.identifier = '{{ request.build_absolute_uri }}.html'
            this.page.title = '{{ object.name }}' + '_title';
        };

        (function () { // DON'T EDIT BELOW THIS LINE
            var d = document, s = d.createElement('script');
            s.src = 'https://mubango-disqus-com.disqus.com/embed.js';
            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
        })();

        function initMap() {
            const address = {lat: {{ object.get_latitude }}, lng: {{ object.get_longitude }}};
            // The map, centered at Uluru
            const map = new google.maps.Map(document.getElementById("map"), {
                zoom: 4,
                center: address,
            });
            // The marker, positioned at Uluru
            const marker = new google.maps.Marker({
                position: address,
                map: map,
            });
        }
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCC0wYfBETVlXyjOqv0WtV6kTvQ-LUi3yU&callback=initMap&callback=initMap"></script>

{% endblock content %}

business/templates/business/clubs/club_search_by_region.html
{% extends 'core/index.html' %}
{% block main_body %}
    <section>
        <div class="block">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="fcsec">
                            <div class="row">
                                {% for obj in object_list %}
                                    <div class="col-lg-3 col-md-4 col-sm-6">
                                        <div class="fc s2">
                                            {% with default_image=STATIC_URL|add:"/mb/static/images/list_default.png" %}
                                            <img src="{{ obj.get_thumbnail|default:default_image }}" alt=""/>
                                            <a href="{{ obj.get_absolute_url }}" title="">{{ obj.name }} <i class="flaticon-wine-glass"></i></a>
                                             {% endwith %}
                                        </div>
                                    </div><!-- Featured Category -->

                                {% endfor %}
                            </div>
                        </div>
                        {% if is_paginated %}
                            <div class="pagination">
                                <ul >

                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                               aria-label="Previous">
                                                <span aria-hidden="true">&laquo;</span>
                                                <span class="sr-only">Previous</span>
                                            </a>
                                        </li>
                                    {% endif %}

                                    <li class="page-item active">
                                        <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
                                            <span class="sr-only">(current)</span>
                                        </a>
                                    </li>

                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{ page_obj.next_page_number }}"
                                               aria-label="Next">
                                                <span aria-hidden="true">&raquo;</span>
                                                <span class="sr-only">Next</span>
                                            </a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>

{%  endblock main_body %}

business/templates/business/clubs/clubs_currently_hot.html
<section>
    <div class="block gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading">
                        <h2>Most Visited Clubs in your Area</h2>
                    </div><!-- Heading -->
                    <div class="catsec">
                        <div class="row" id="masonry">
                            {% for obj in club_currently_hot_list %}
                                <div class="col-lg-4">
                                    <div class="category">
                                        {% with default_image=STATIC_URL|add:"/mb/static/images/default.png" %}
                                            <a href="{{ obj.get_absolute_url }}"><img
                                                    src="{{ obj.get_thumbnail|default:default_image }}" alt=""/></a>
                                        {% endwith %}
                                        <div class="cattitle">
                                            <h3><a href="{{ obj.get_absolute_url }}" title="">{{ obj.name }}</a></h3>
                                        </div>

                                    </div><!-- Category -->
                                </div>
                            {% endfor %}
                        </div>
                    </div><!-- Cat Sec -->
                </div>
            </div>
        </div>
    </div>
</section>